spring.application.name=tripverse

spring.datasource.url=jdbc:postgres://192.168.15.164:5432/db
spring.datasource.username=user
spring.datasource.password=password

spring.jpa.database-platform=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true