spring.application.name=apptrip

server.port=${SERVER_PORT:5010}
server.forward-headers-strategy=${SERVER_FORWARD_HEADERS_STRATEGY:framework}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:postgres}

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.show_sql=${SPRING_JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=${SPRING_JPA_FORMAT_SQL:true}

security.secret-key=${SECURITY_SECRET_KEY:bXkgc2VjdXJlIGtleSBmb3IgYXBwdHJpcCBhcHBsaWNhdGlvbiAyMDI1}
geocode.api-key=${GEOCODE_API_KEY:691f70d4b6f7b354059268umf0f8868}

apptrip.uploads.path=${APPTRIP_UPLOADS_PATH:./uploads}

